### ISSUE TITLE
Some spelling errors

### ISSUE THREAD

**Issue by xstt** [Bit-Nation/BITNATION-Pangea-Themes#13]
DApp Library: should read BITNATION Notary not BITANATION Notary

Public Notary instead of Blockchain Notary, on the left side menu. Inside the Public Notary, page title should read Public Notary with a capital N.

On the left side menu, should read Basic Income, instead of Basicincome.co

**Comment by n00bsys0p** [comment]
@oskardahlberg Can you check the code in the linked PR for us so we can sign off and publish this please? Thanks!
