### ISSUE TITLE
Pangea public instance (bitnation.world) login not working

### ISSUE THREAD

**Issue by dgrmunch** [Bit-Nation/BITNATION-Pangea-Themes#24]
I am using Firefox 41.0.2.

**Comment by ccmawo** [comment]
Any error message? 
The pangea javascript libraries will open a connection to a remote server with port 6976. Please check whether your firewall allow this.

**Comment by dgrmunch** [comment]
I'll try to see any possible Javascript error on the JS console and let you know more.

**Comment by hsribei** [comment]
Same here. I enter the passphrase, hit "Login", and it just clears the passphrase.

**Comment by ccmawo** [comment]
This time remote server was down. Thanks for the hint.

**Comment by derdela** [comment]
Looks like this server: http://eu4.woll-e.net:6976/nhz is down again.

**Comment by ccmawo** [comment]
Thanks for reporting!
Server is permanently down.
DNS record changed. Now eu4.woll-e.net points to a new server.
